### ISSUE TITLE
ultraFastSend

### ISSUE THREAD

**Issue by artarasaneh** [mahdiidea/SmsIrLaravel6#1]
سلام 
ممنونم تنها پکیجی که روی لاراول ۶ برای من نصب شد پکیج شما بود
لطف کنید بفرمایید 
از
 ultraFastSend
 چطور برای ارسال پیام همراه با قالب تعریف شده استفاده کنم ؟

**Comment by rajabit** [comment]
سلام من برای پکیج یه داکیومنت کامل نصب و کانفیگ و استفاده نوشتم 
https://github.com/mahdiidea/SmsIrLaravel6/blob/master/README.md
لذت ببرید :)
